# Config file for automatic testing at travis-ci.org

sudo: false
language: python

jobs:
    include:
      - python: 3.6
        env: TOX_ENV=linting
      - python: 2.7
        env: TOX_ENV=py27
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36

install:
  - pip install -U pip
  - pip install -U setuptools tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
